// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("ComVu.Core")>]
[<assembly: GuidAttribute("2e3bf328-3993-48c4-9437-d3d5662bd33a")>]
[<assembly: AssemblyProductAttribute("ComVu")>]
[<assembly: AssemblyVersionAttribute("0.1.2")>]
[<assembly: AssemblyFileVersionAttribute("0.1.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ComVu.Core"
    let [<Literal>] Guid = "2e3bf328-3993-48c4-9437-d3d5662bd33a"
    let [<Literal>] AssemblyProduct = "ComVu"
    let [<Literal>] AssemblyVersion = "0.1.2"
    let [<Literal>] AssemblyFileVersion = "0.1.2"
    let [<Literal>] AssemblyInformationalVersion = "0.1.2"
