// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ComVu.Core")>]
[<assembly: AssemblyProductAttribute("ComVu")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ComVu.Core"
    let [<Literal>] AssemblyProduct = "ComVu"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
