// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ComVu")]
[assembly: AssemblyProductAttribute("ComVu")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "ComVu";
        internal const System.String AssemblyProduct = "ComVu";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0";
    }
}
